core/urls.py
from django.contrib import admin
from django.urls import include, path
from django.urls import path, include


urlpatterns = [
    # path("admin/", admin.site.urls),
    path("cms/", include("src.urls.cms")),
    path("", include("src.urls.web")),
]

src/models/Contact.py
from django.db import models


class Contact(models.Model):
    fullname = models.CharField(max_length=255, null=True)
    email = models.CharField(max_length=255, null=True)
    phone = models.CharField(max_length=255, null=True)
    subject = models.CharField(max_length=255, null=True)
    message = models.TextField(null=True)
    created_at = models.DateTimeField(null=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, auto_now=True)

src/models/Product.py
from django.db import models

from src.models.ProductCategory import ProductCategory


class Product(models.Model):
    product_category = models.ForeignKey(ProductCategory, on_delete=models.RESTRICT)
    name = models.CharField(max_length=255, null=True)
    image = models.TextField(null=True)
    description = models.CharField(max_length=255, null=True)
    price = models.IntegerField(default=0)
    is_active = models.IntegerField(default=1)
    created_at = models.DateTimeField(null=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, auto_now=True)

src/models/ProductCategory.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(null=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, auto_now=True)

src/models/ProductShopify.py
from django.db import models


class ProductShopify(models.Model):
    title = models.TextField(null=True)
    body_html = models.TextField(null=True)
    vendor = models.TextField(null=True)
    product_type = models.TextField(null=True)
    created_at = models.TextField(null=True)
    handle = models.TextField(null=True)
    updated_at = models.TextField(null=True)
    published_at = models.TextField(null=True)
    template_suffix = models.TextField(null=True)
    status = models.TextField(null=True)
    published_scope = models.TextField(null=True)
    tags = models.TextField(null=True)
    admin_graphql_api_id = models.TextField(null=True)
    image = models.TextField(null=True)
    

src/models/ProductShopifyImage.py
from django.db import models
from src.models import ProductShopify

class ProductShopifyImage(models.Model):
    product = models.ForeignKey(ProductShopify, on_delete=models.CASCADE)
    position = models.IntegerField(default=0)
    created_at = models.TextField(null=True)
    updated_at = models.TextField(null=True)
    alt = models.TextField(null=True)
    width = models.IntegerField(default=0)
    height = models.IntegerField(default=0)
    src = models.TextField(null=True)
    variant_ids = models.TextField(null=True)
    admin_graphql_api_id = models.TextField(null=True)

src/models/ProductShopifyOption.py
from django.db import models
from src.models import ProductShopify


class ProductShopifyOption(models.Model):
    product = models.ForeignKey(ProductShopify, on_delete=models.CASCADE)
    name = models.TextField(null=True)
    position = models.IntegerField(default=0)
    values = models.TextField(null=True)

src/models/ProductShopifyVariant.py
from django.db import models

from src.models import ProductShopify, ProductShopifyImage


class ProductShopifyVariant(models.Model):
    product = models.ForeignKey(ProductShopify, on_delete=models.CASCADE)
    title = models.TextField(null=True)
    price = models.TextField(null=True)
    sku = models.TextField(null=True)
    position = models.IntegerField(default=0)
    inventory_policy = models.TextField(null=True)
    compare_at_price = models.TextField(null=True)
    fulfillment_service = models.TextField(null=True)
    inventory_management = models.TextField(null=True)
    option1 = models.TextField(null=True)
    option2 = models.TextField(null=True)
    option3 = models.TextField(null=True)
    created_at = models.TextField(null=True)
    updated_at = models.TextField(null=True)
    taxable = models.IntegerField(default=0)
    barcode = models.TextField(null=True)
    grams = models.IntegerField(default=0)
    image = models.ForeignKey(ProductShopifyImage, on_delete=models.RESTRICT,null=True)
    weight = models.FloatField(default=0)
    weight_unit = models.TextField(null=True)
    inventory_item_id = models.IntegerField(default=0)
    inventory_quantity = models.IntegerField(default=0)
    old_inventory_quantity = models.IntegerField(default=0)
    requires_shipping = models.IntegerField(default=0)
    admin_graphql_api_id = models.TextField(null=True)
    presentment_prices = models.TextField(null=True)

src/models/UserClient.py
from django.db import models


class UserClient(models.Model):
    email = models.CharField(max_length=255, unique=True)
    password = models.CharField(max_length=255, null=True)
    name = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(null=True, auto_now_add=True)
    updated_at = models.DateTimeField(null=True, auto_now=True)

src/templates/cms/pages/account/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'cms-html/assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'cms-html/assets/vendors/bootstrap-icons/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'cms-html/assets/css/app.css' %}">
    <link rel="stylesheet" href="{% static 'cms-html/assets/css/pages/auth.css' %}">
</head>

<body>
    <div id="auth">

        <div class="row h-100">
            <div class="col-lg-5 col-12">
                <div id="auth-left">

                    <h1 class="auth-title">Log in.</h1>

                    <form action="" method="post">{% csrf_token %} 
                        <div class="form-group position-relative has-icon-left mb-4">
                            <input type="text" class="form-control form-control-xl" placeholder="Username" name="username">
                            <div class="form-control-icon">
                                <i class="bi bi-person"></i>
                            </div>
                        </div>
                        <div class="form-group position-relative has-icon-left mb-4">
                            <input type="password" class="form-control form-control-xl" placeholder="Password" name="password">
                            <div class="form-control-icon">
                                <i class="bi bi-shield-lock"></i>
                            </div>
                        </div>
                        <div class="form-check form-check-lg d-flex align-items-end">
                            <input class="form-check-input me-2" type="checkbox" value="" id="flexCheckDefault">
                            <label class="form-check-label text-gray-600" for="flexCheckDefault">
                                Keep me logged in
                            </label>
                        </div>
                        <button class="btn btn-primary btn-block btn-lg shadow-lg mt-5">Log in</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-7 d-none d-lg-block">
                <div id="auth-right">

                </div>
            </div>
        </div>

    </div>
</body>

</html>

src/templates/cms/pages/admin/create.html
{% extends "cms/partials/layout.html" %} {% block content %}
<h1>Admin manager</h1>
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Create</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form class="form" id="form">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Group
                                        </label>
                                        <select class="js-example-basic-multiple form-control" name="groups"
                                            multiple="multiple">
                                            {% for group in groups %}
                                            <option value="{{group.id}}">
                                                {{group.name}}
                                            </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Permissions</label>
                                        <select class="js-example-basic-multiple form-control" name="permissions"
                                            multiple="multiple">
                                            {% for permission in permissions %}
                                            <option value="{{permission.codename}}">
                                                {{permission.name}}
                                            </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Username</label>
                                        <input type="text" class="form-control" name="username" />
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Password</label>
                                        <input type="text" class="form-control" name="password" />
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Name</label>
                                        <input type="text" class="form-control" name="name" />
                                    </div>
                                </div>
                                <div class="col-12 d-flex justify-content-start mt-3">
                                    <button type="submit" class="btn btn-primary me-1 mb-1">
                                        Submit
                                    </button>
                                    <button type="reset" class="btn btn-light-secondary me-1 mb-1">
                                        Reset
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block js %}
<script>
    $(document).ready(function () {
        $('.js-example-basic-multiple').select2();
    });
    $(document).on('submit', '#form', function () {
        var formData = new FormData()

        formData.append('csrfmiddlewaretoken', $('[name="csrfmiddlewaretoken"]').val() || "")

        $('#form').find('input,textarea,select').each(function (i) {
            if ($(this).attr('type') == 'file') {
                formData.append($(this).attr('name'), $(this)[0].files[0] || "")
            } else {
                formData.append($(this).attr('name'), $(this).val() || "")
            }
        })

        $.ajax({
            url: '',
            data: formData,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function (data) {
                console.log(data)
                alert('Successfully')
                window.location.href = window.location.href 
            },
            error: function (data, textStatus, jqXHR) {
                var errors = data.responseJSON.errors
                console.log(errors)
                var message = "Errors: \r\n"

                for (const property in errors) {
                    message += (property + ": " + errors[property][0] + "\r\n")
                }

                alert(message);
            },
        });
        return false
    })
</script>
{% endblock %}

src/templates/cms/pages/admin/index.html
{% extends "cms/partials/layout.html" %} {% block content %}
<h1>Admin</h1>
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Index</h4>
    </div>
    <div class="card-header"><a href="{% url "cms:admin.create" %}">Create</a></div>
    <div class="card-body">
        <table class="table table-striped" id="table1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Username</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for x in admins %}
                <tr>
                    <td>{{x.id}}</td>
                    <td>{{x.username}}</td>
                    <td><a href="{% url "cms:admin.update" id=x.id %}" >Update</a> / <a href="#" class="delete" data-id="{{x.id}}">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    $(document).on('click', '.delete', function() {
        if (confirm('Are you sure?')) {
            var formData = new FormData()
            formData.append(
                "csrfmiddlewaretoken",
                $('[name="csrfmiddlewaretoken"]').val() || ""
            );
            formData.append('id', $(this).data('id'))
            var element = $(this).parents('tr')
            $.ajax({
                url: "{% url 'cms:admin.delete'  %}",
                data: formData,
                processData: false,
                contentType: false,
                type: 'POST',
                success: function(data) {
                    element.hide()
                },
                error: function(data, textStatus, jqXHR) {
                    alert('Không thể xoá nội dung này')
                },
            });
            return false
        }
    })
</script>
{% endblock %}

src/templates/cms/pages/admin/update.html
{% extends "cms/partials/layout.html" %} {% block content %}
<h1>Admin manager</h1>
<section id="multiple-column-form">
    <div class="row match-height">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Update</h4>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        <form class="form" id="form">
                            <div class="row">
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Group
                                        </label>
                                        <select class="js-example-basic-multiple form-control" name="groups"
                                            multiple="multiple">
                                            {% for group in groups %}
                                            <option {% if group.id in groupIds %}selected{% endif %} value="{{group.id}}">
                                                {{group.name}}
                                            </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Permissions</label>
                                        <select class="js-example-basic-multiple form-control" name="permissions"
                                            multiple="multiple">
                                            {% for permission in permissions %}
                                            <option {% if permission.id in permissionIds %}selected{% endif %} value="{{permission.codename}}">
                                                {{permission.name}}
                                            </option>
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Username</label>
                                        <input type="text" class="form-control" name="username" value="{{admin.username}}"/>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Password</label>
                                        <input type="text" class="form-control" name="password"  value=""/>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="first-name-column">Name</label>
                                        <input type="text" class="form-control" name="name" value="{{admin.first_name}}"/>
                                    </div>
                                </div>
                                <div class="col-12 d-flex justify-content-start mt-3">
                                    <button type="submit" class="btn btn-primary me-1 mb-1">
                                        Submit
                                    </button>
                                    <button type="reset" class="btn btn-light-secondary me-1 mb-1">
                                        Reset
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block js %}
<script>
    $(document).ready(function () {
        $('.js-example-basic-multiple').select2();
    });
    $(document).on('submit', '#form', function () {
        var formData = new FormData()

        formData.append('csrfmiddlewaretoken', $('[name="csrfmiddlewaretoken"]').val() || "")

        $('#form').find('input,textarea,select').each(function (i) {
            if ($(this).attr('type') == 'file') {
                formData.append($(this).attr('name'), $(this)[0].files[0] || "")
            } else {
                if($(this).val()){
                    formData.append($(this).attr('name'), $(this).val() || "")
                }
            }
        })

        $.ajax({
            url: '',
            data: formData,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function (data) {
                console.log(data)
                alert('Successfully')
                window.location.href = window.location.href
            },
            error: function (data, textStatus, jqXHR) {
                var errors = data.responseJSON.errors
                console.log(errors)
                var message = "Errors: \r\n"

                for (const property in errors) {
                    message += (property + ": " + errors[property][0] + "\r\n")
                }

                alert(message);
            },
        });
        return false
    })
</script>
{% endblock %}

src/templates/cms/pages/contact/index.html
{% extends "cms/partials/layout.html" %} {% block content %}
<h1>Contact</h1>
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Index</h4>
    </div>
    <div class="card-body">
        <table class="table table-striped" id="table1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Subject</th>
                    <th>Message</th>
                </tr>
            </thead>
            <tbody>
                {% for x in contacts %}
                <tr>
                    <td>{{x.id}}</td>
                    <td>{{x.fullname}}</td>
                    <td>{{x.email}}</td>
                    <td>{{x.phone}}</td>
                    <td>{{x.subject}}</td>
                    <td>{{x.message}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

src/templates/cms/pages/dashboard/index.html
{% extends "cms/partials/layout.html" %}

{% block content %}
<h1>Dashboard</h1>
{% endblock %}

src/templates/cms/pages/productShopify/index.html
{% extends "cms/partials/layout.html" %} {% block content %}
<h1>Product shopify</h1>
<div class="card">
    <div class="card-header">
        <h4 class="card-title">Index</h4>
    </div>
    <div class="card-header"><a href="{% url 'cms:productShopify.sync' %}">Sync</a></div>
    <div class="card-body">
        <table class="table table-striped" id="table1">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                {% for x in products %}
                <tr>
                    <td>{{x.id}}</td>
                    <td>{{x.title}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

src/templates/web/pages/home.html
{% extends "web/partials/layout.html" %}
{% load helpers %}
{% load static %}
{% block css %}
<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        gap: 1vw;
        min-height: 90vh;
        padding: 5vw;
    }

    label {
        display: block;
    }

    form {
        display: flex;
        flex-direction: column;
        gap: 0.5vw;
    }

    input {
        width: 20vw;
        height: 2vw;
    }

    textarea {
        width: 20vw;
        height: 5vw;
    }

    button {
        width: 20.4vw;
        height: 2vw;
    }

    .list-product {
        width: 100%;
        display: grid;
        grid-template-columns: 1fr 1fr 1fr 1fr;
        gap: 3vw;
    }

    .product {
        min-height: 10vw;
        box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
        padding: 1vw;
        text-decoration: none;
        color: inherit;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
    {% for productCategory in productCategories %}
    <h1>{{productCategory.name}}</h1>
    <div class="list-product">
        {% for product in productCategory.product_set.all %}
        {% if product.is_active == 1 %}
        <a href="{% url 'web:productDetail' product.name|slug product.id %}" class="product">
            <div>
                <img src="{% if product.image %}{% static "uploads/images/" %}{{product.image }}{% else %}{% static "product.jpg" %}{% endif %}"
                    alt="" width="100%">
            </div>
            <h4>{{product.name}}</h4>
            <div>{{product.description}}</div>
            <br />
            <div>
                <b>{{product.price | formatCurrency}} VNĐ</b>
            </div>
        </a>
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
    <hr>
    <h2>Contact form</h2>
    <form action="" id="form">
        <div>
            <label for="">Fullname</label>
            <input type="text" name="fullname" />
        </div>
        <div>
            <label for="">Email</label>
            <input type="email" name="email" />
        </div>
        <div>
            <label for="">Phone</label>
            <input type="number" name="phone" />
        </div>
        <div>
            <label for="">Subject</label>
            <input type="text" name="subject" />
        </div>
        <div>
            <label for="">Message</label>
            <textarea name="message" id="" cols="30" rows="50"></textarea>
        </div>
        <div>
            <button>Submit</button>
        </div>
    </form>
</div>
{% endblock %}
{% block js %}
<script>
    $(document).ready(function () {
        $(".js-example-basic-multiple").select2();
    });
    $(document).on("submit", "#form", function () {
        var formData = new FormData();

        formData.append(
            "csrfmiddlewaretoken",
            $('[name="csrfmiddlewaretoken"]').val() || ""
        );

        $("#form")
            .find("input,textarea,select")
            .each(function (i) {
                if ($(this).attr("type") == "file") {
                    formData.append(
                        $(this).attr("name"),
                        $(this)[0].files[0] || ""
                    );
                } else {
                    formData.append(
                        $(this).attr("name"),
                        $(this).val() || ""
                    );
                }
            });

        $.ajax({
            url: "",
            data: formData,
            processData: false,
            contentType: false,
            type: "POST",
            success: function (data) {
                console.log(data);
                alert("Successfully");
                window.location.href = window.location.href;
            },
            error: function (data, textStatus, jqXHR) {
                var errors = data.responseJSON.errors;
                console.log(errors);
                var message = "";

                for (const property in errors) {
                    message +=
                        property + ": " + errors[property][0] + "\r\n";
                }

                alert(message);
            },
        });
        return false;
    });
</script>
{% endblock %}

src/templates/web/pages/productShopify.html
{% extends "web/partials/layout.html" %}
{% load helpers %}
{% load static %}
{% block css %}
<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        gap: 1vw;
        min-height: 50vh;
        padding: 5vw;
    }

    label {
        display: block;
    }

    form {
        display: flex;
        flex-direction: column;
        gap: 0.5vw;
    }

    input {
        width: 20vw;
        height: 2vw;
    }

    textarea {
        width: 20vw;
        height: 5vw;
    }

    button {
        width: 20.4vw;
        height: 2vw;
    }

    .list-product {
        width: 100%;
        display: grid;
        grid-template-columns: 1fr 1fr 1fr 1fr;
        gap: 3vw;
    }

    .product {
        min-height: 10vw;
        box-shadow: rgba(0, 0, 0, 0.35) 0px 5px 15px;
        padding: 1vw;
        text-decoration: none;
        color: inherit;
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="list-product">
        {% for product in products %}
        <a href="{% url 'web:productShopifyDetail' product.title|slug product.id %}" class="product">
            <div>
                <img src="{% if product.image %}{{product.image}}{% else %}{% static "product.jpg" %}{% endif %}"
                    alt="" width="100%">
            </div>
            <h4>{{product.title}}</h4>
            <div>{{product.productshopifyvariant_set.first.price}} $</div>

        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

src/templates/web/pages/productShopifyDetail.html
{% extends "web/partials/layout.html" %}
{% load helpers %}
{% load static %}
{% block css %}
<style>
    .container {
        display: flex;
        justify-content: center;
        align-items: center;
        flex-direction: column;
        gap: 1vw;
        min-height: 50vh;
        padding: 5vw 20vw;
        text-align: center
    }

    tr {
        display: flex;
        gap: 5vw;
        width: 70vw;
        margin-bottom: 2vw
    }

    td {
        flex: 1
    }

    thead {
        font-weight: bold
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
    <div>
        <img src="{% if product.image %}{{product.image}}{% else %}{% static "product.jpg" %}{% endif %}" alt=""
            width="50%">
    </div>
    <h4>{{product.title}}</h4>
    <div>{{product.body_html}}</div>
    <div><b>Vendor:</b> {{product.vendor}}</div>
    <div> <b>Type:</b> {{product.product_type}}</div>
    <div> <b>Tags:</b> {{product.tags}}</div>
    <h3>Variant:</h3>
    <table>
        <thead>
            <tr>
                <td>Title</td>
                <td>Weight</td>
                <td>Price</td>
                <td></td>
            </tr>
        </thead>
        <tbody>
            {% for variant in product.productshopifyvariant_set.all %}
            <tr>
                <td>{{variant.title}}</td>
                <td>{{variant.grams}} g</td>
                <td>{{variant.price}} $</td>
                <td><button class="js-addToCart" data-id="{{variant.id}}">Add to cart</button></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<input type="hidden" id="js-data" data-product_id="{{product.id}}"
    data-url_add_to_cart="{% url 'web:productShopifyDetail.addToCart' %}">
{% endblock %}
{% block js %}
<script>
    $(document).on("click", ".js-addToCart", function () {
        var formData = new FormData()

        formData.append('csrfmiddlewaretoken', $('[name="csrfmiddlewaretoken"]').val() || "")
        formData.append('variant_id', $(this).data("id") || "")

        $.ajax({
            url: $('#js-data').data("url_add_to_cart"),
            data: formData,
            processData: false,
            contentType: false,
            xhrFields: {
                withCredentials: true
            },
            type: 'POST',
            success: function (data) {
                console.log(data.cart)
                setCartQuantityProduct(data.cart)
            },
            error: function (data, textStatus, jqXHR) {
                var errors = data.responseJSON.errors
                console.log(errors)
                var message = ""

                for (const property in errors) {
                    message += (property + ": " + errors[property][0] + "\r\n")
                }

                alert(message);
            },
        });
    })
</script>
{% endblock %}